# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5c9829696b1eba70dc7603b435481a3d62bbed47b6df2bf621961af78cd7015279e3955b9357947aa9cb20ac83e0fa53166b49bb35f6d6977e7e5ac28200822

test:
  secret_key_base: 8ce1f1f77b61a00b9b2a8f5fb293b8d643fdca1bca24e0c4d52c39e5ad50a608d57a3ac9e2fbade9aafff3c83323838025c7963bc57705b9b9cc1d51a6631983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
